---
title: "simulations"
author: "Zhaohua Chunyu"
date: "2022-11-03"
output: github_document
---

```{r, include = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Simulations

Here's our function from before.

```{r}
sim_mean_sd = function(n_obs, miu = 7, sigma = 4) {
  
  x = rnorm(n = n_obs, mean = miu, sd = sigma)

  tibble(
    mu_hat = mean(x), ## estimated mean of true mean
    sigma_hat = sd(x) ## estimated sigma of true sigma
  )
  
}
```


How did we use this before?

```{r}
sim_mean_sd(n_obs = 30)
```


How can we use this now?

Let's start with a for loop!

```{r}
## Create an output vector with 100 empty spots
output = vector("list", length = 100)

##100 hundred times I ran sim_mean_sd with number of observations equals to 30 and save the output each time 
for (i in 1:100) {
  output[[i]] = sim_mean_sd(n_obs = 30)
  
}

## Create 1 dataframe with 100 rows binding 100 dataframes
bind_rows(output)
```


Let's use list colomns instead.

```{r}
sim_results_df = 
  expand_grid(
    sample_size = 30,
    iteration = 1:100
    ) %>% 
  mutate(
    estimate_df = map(sample_size, sim_mean_sd)
  ) %>% 
  unnest(estimate_df)
```

```{r}
sim_results_df %>% 
  ggplot(aes(x = mu_hat)) +
  geom_density()
```


## What about changing the sample size?

I need a input list with lots of sample sizes.

```{r}
sim_results_df = 
  expand_grid(
    sample_size = c(30, 60, 120, 240),
    iteration = 1:1000
  ) %>% 
  mutate(
    estimate_df = map(sample_size, sim_mean_sd)
  ) %>% 
  unnest(estimate_df)
```

```{r}
sim_results_df %>% 
  mutate(
    sample_size = str_c("N = ", sample_size),
    sample_size = fct_inorder(sample_size)
  ) %>% 
  ggplot(aes(x = sample_size, y = mu_hat)) + 
  geom_violin()
```

```{r}
sim_results_df %>% 
  mutate(
    sample_size = str_c("N = ", sample_size),
    sample_size = fct_inorder(sample_size)
  ) %>% 
  group_by(sample_size) %>% 
  summarize(
    emp_st_error = sd(mu_hat)
  )
```



## Let's see two inputs...
```{r}
sim_results_df = 
  expand_grid(
    sample_size = c(30, 60, 120, 240),
    true_sigma = c(6, 3),
    iteration = 1:1000
  ) %>% 
  mutate(
    estimate_df = 
      map2(.x = sample_size, .y = true_sigma, ~sim_mean_sd(n_obs = .x, sigma = .y))
  ) %>% 
  unnest(estimate_df)
```

```{r}
sim_results_df %>% 
  mutate(
    sample_size = str_c("N = ", sample_size),
    sample_size = fct_inorder(sample_size)
  ) %>% 
  ggplot(aes(x = sample_size, y = mu_hat)) + 
  geom_violin() + 
  facet_grid(. ~ true_sigma)
```







